[package]
name = "dlipower"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = {version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["cookies"]}
md-5 = "0.10"
scraper = "0.17"
regex = "1"
